import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { HttpClientModule} from '@angular/common/http';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { ProductComponent } from './products/product.component';
import { MyUpperPipe } from './products/myUpperCase.pipe';
import { DiscountPipe } from './products/discountedPrice.pipe';
import { ProductFilter } from './products/productFilter.pipe';
import { StarComponent } from './shared/star.component';
import { ProductService } from './products/product.services';
import { OrderComponent } from './orders/order.component';
import { NotFoundComponent } from './shared/notFound.component';
import { ProductDetailComponent } from './products/product-detail.component';
import { ProductModule } from './products/product.module';


@NgModule({
    // all module
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        HttpClientModule,
        RouterModule.forRoot([
            {path: 'products', component: ProductComponent},
            {path: 'products/:id', component: ProductDetailComponent},
            {path: 'orders', component: OrderComponent},
            {path: 'home', component: HomeComponent},
            {path: '', redirectTo: 'home', pathMatch: 'full'},
            {path: '**', component: NotFoundComponent}
        ]),
        ProductModule
    ],
    // all components & pipe
    declarations: [
        AppComponent,
        HomeComponent,
        ProductComponent,
        MyUpperPipe,
        DiscountPipe,
        ProductFilter,
        StarComponent,
        OrderComponent,
        NotFoundComponent,
        ProductDetailComponent
    ],

    // only first component
    bootstrap: [
        AppComponent
    ],

    // all services
    providers: [
        ProductService
    ]
})

export class AppModule {

}


/*
if(product){

}
*/
